version: "3.9"
services:
  backend:
    build: .
    image: finestrike83/apps-didik:v2.0
    restart: always
    env_file:
      - .env
    ports:
      - "3000"
    volumes:
      - app-data:/app/public/images
  web:
    build: ./nginx
    image: finestrike83/web-proxy
    restart: always
    ports:
    - "80:80"
    depends_on:
    - backend
volumes:
  app-data: